// AUTO-GENERATED by generate_metadata.py; do not edit by hand.
// To change the gallery: edit photos.meta.json and/or photography/, then re-run
//   python3 generate_metadata.py
window.photoData = {
  "sections": [
    {
      "title": "Architecture",
      "slug": "architecture",
      "photos": [
        {
          "src": "photography/osaka-lion-shrine.jpg",
          "thumb": "photography/thumbs/osaka-lion-shrine.jpg",
          "preview": "photography/variants/osaka-lion-shrine-9e727533a930f1b3-1600.jpg",
          "sources": {
            "jpeg": [
              {
                "src": "photography/variants/osaka-lion-shrine-9e727533a930f1b3-600.jpg",
                "width": 400,
                "height": 600
              },
              {
                "src": "photography/variants/osaka-lion-shrine-9e727533a930f1b3-1200.jpg",
                "width": 800,
                "height": 1200
              },
              {
                "src": "photography/variants/osaka-lion-shrine-9e727533a930f1b3-1600.jpg",
                "width": 1066,
                "height": 1600
              },
              {
                "src": "photography/variants/osaka-lion-shrine-9e727533a930f1b3-2400.jpg",
                "width": 1600,
                "height": 2400
              }
            ],
            "webp": [
              {
                "src": "photography/variants/osaka-lion-shrine-9e727533a930f1b3-600.webp",
                "width": 400,
                "height": 600
              },
              {
                "src": "photography/variants/osaka-lion-shrine-9e727533a930f1b3-1200.webp",
                "width": 800,
                "height": 1200
              },
              {
                "src": "photography/variants/osaka-lion-shrine-9e727533a930f1b3-1600.webp",
                "width": 1066,
                "height": 1600
              },
              {
                "src": "photography/variants/osaka-lion-shrine-9e727533a930f1b3-2400.webp",
                "width": 1600,
                "height": 2400
              }
            ]
          },
          "alt": "One eye of the lion at Namba Yasaka Shrine appears through hanging paper slips.",
          "theme": "Architecture",
          "place": "Osaka, Japan",
          "order": 1,
          "width": 1723,
          "height": 2585,
          "camera": "SONY ILCE-7M4",
          "lens": "SIGMA 24-70mm F2.8 DG DN Art 019",
          "focalLength": "30.7mm",
          "shutterSpeed": "1/250s",
          "aperture": "f/4.5",
          "iso": "ISO 100",
          "date": "2025:05:29 00:42:16"
        },
        {
          "src": "photography/oculus-nyc.jpg",
          "thumb": "photography/thumbs/oculus-nyc.jpg",
          "preview": "photography/variants/oculus-nyc-48488522259ed993-1600.jpg",
          "sources": {
            "jpeg": [
              {
                "src": "photography/variants/oculus-nyc-48488522259ed993-600.jpg",
                "width": 400,
                "height": 600
              },
              {
                "src": "photography/variants/oculus-nyc-48488522259ed993-1200.jpg",
                "width": 800,
                "height": 1200
              },
              {
                "src": "photography/variants/oculus-nyc-48488522259ed993-1600.jpg",
                "width": 1067,
                "height": 1600
              },
              {
                "src": "photography/variants/oculus-nyc-48488522259ed993-2400.jpg",
                "width": 1600,
                "height": 2400
              }
            ],
            "webp": [
              {
                "src": "photography/variants/oculus-nyc-48488522259ed993-600.webp",
                "width": 400,
                "height": 600
              },
              {
                "src": "photography/variants/oculus-nyc-48488522259ed993-1200.webp",
                "width": 800,
                "height": 1200
              },
              {
                "src": "photography/variants/oculus-nyc-48488522259ed993-1600.webp",
                "width": 1067,
                "height": 1600
              },
              {
                "src": "photography/variants/oculus-nyc-48488522259ed993-2400.webp",
                "width": 1600,
                "height": 2400
              }
            ]
          },
          "alt": "The Oculus structure with One World Trade Center rising in the background in New York City.",
          "theme": "Architecture",
          "place": "New York City",
          "order": 2,
          "width": 3847,
          "height": 5770,
          "camera": "FUJIFILM X100V",
          "lens": "23mm F2 Fixed Lens",
          "focalLength": "23mm",
          "shutterSpeed": "1/125s",
          "aperture": "f/11",
          "iso": "ISO 200",
          "date": "2025:02:01 15:18:36"
        },
        {
          "src": "photography/parking-exit.jpg",
          "thumb": "photography/thumbs/parking-exit.jpg",
          "preview": "photography/variants/parking-exit-024adf44f1f9e13a-1600.jpg",
          "sources": {
            "jpeg": [
              {
                "src": "photography/variants/parking-exit-024adf44f1f9e13a-600.jpg",
                "width": 600,
                "height": 400
              },
              {
                "src": "photography/variants/parking-exit-024adf44f1f9e13a-1200.jpg",
                "width": 1200,
                "height": 800
              },
              {
                "src": "photography/variants/parking-exit-024adf44f1f9e13a-1600.jpg",
                "width": 1600,
                "height": 1067
              },
              {
                "src": "photography/variants/parking-exit-024adf44f1f9e13a-2400.jpg",
                "width": 2400,
                "height": 1600
              }
            ],
            "webp": [
              {
                "src": "photography/variants/parking-exit-024adf44f1f9e13a-600.webp",
                "width": 600,
                "height": 400
              },
              {
                "src": "photography/variants/parking-exit-024adf44f1f9e13a-1200.webp",
                "width": 1200,
                "height": 800
              },
              {
                "src": "photography/variants/parking-exit-024adf44f1f9e13a-1600.webp",
                "width": 1600,
                "height": 1067
              },
              {
                "src": "photography/variants/parking-exit-024adf44f1f9e13a-2400.webp",
                "width": 2400,
                "height": 1600
              }
            ]
          },
          "alt": "A red EXIT sign on a concrete pillar stands among diagonal cables, painted arrows, and empty parking spaces.",
          "theme": "Architecture",
          "place": "",
          "order": 3,
          "width": 6707,
          "height": 4471,
          "camera": "SONY ILCE-7M4",
          "lens": "SIGMA 60-600mm F4.5-6.3 DG DN OS Sports 023",
          "focalLength": "600mm",
          "shutterSpeed": "1/80s",
          "aperture": "f/6.3",
          "iso": "ISO 12800",
          "date": "2025:08:28 23:12:29"
        },
        {
          "src": "photography/uji-station-arches.jpg",
          "thumb": "photography/thumbs/uji-station-arches.jpg",
          "preview": "photography/variants/uji-station-arches-d52c7fdf21c885c9-1600.jpg",
          "sources": {
            "jpeg": [
              {
                "src": "photography/variants/uji-station-arches-d52c7fdf21c885c9-600.jpg",
                "width": 480,
                "height": 600
              },
              {
                "src": "photography/variants/uji-station-arches-d52c7fdf21c885c9-1200.jpg",
                "width": 960,
                "height": 1200
              },
              {
                "src": "photography/variants/uji-station-arches-d52c7fdf21c885c9-1600.jpg",
                "width": 1280,
                "height": 1600
              },
              {
                "src": "photography/variants/uji-station-arches-d52c7fdf21c885c9-2336.jpg",
                "width": 1869,
                "height": 2336
              }
            ],
            "webp": [
              {
                "src": "photography/variants/uji-station-arches-d52c7fdf21c885c9-600.webp",
                "width": 480,
                "height": 600
              },
              {
                "src": "photography/variants/uji-station-arches-d52c7fdf21c885c9-1200.webp",
                "width": 960,
                "height": 1200
              },
              {
                "src": "photography/variants/uji-station-arches-d52c7fdf21c885c9-1600.webp",
                "width": 1280,
                "height": 1600
              },
              {
                "src": "photography/variants/uji-station-arches-d52c7fdf21c885c9-2336.webp",
                "width": 1869,
                "height": 2336
              }
            ]
          },
          "alt": "Repetitive concrete arches creating a tunnel effect inside Uji Station, Japan.",
          "theme": "Architecture",
          "place": "Uji, Japan",
          "order": 4,
          "width": 1869,
          "height": 2336,
          "camera": "SONY ILCE-7M4",
          "lens": "SIGMA 24-70mm F2.8 DG DN Art 019",
          "focalLength": "24mm",
          "shutterSpeed": "1/400s",
          "aperture": "f/4",
          "iso": "ISO 400",
          "date": "2025:06:01 02:11:11"
        },
        {
          "src": "photography/sunset-coda.jpg",
          "thumb": "photography/thumbs/sunset-coda.jpg",
          "preview": "photography/variants/sunset-coda-6f51553249e9756f-1600.jpg",
          "sources": {
            "jpeg": [
              {
                "src": "photography/variants/sunset-coda-6f51553249e9756f-600.jpg",
                "width": 600,
                "height": 337
              },
              {
                "src": "photography/variants/sunset-coda-6f51553249e9756f-1200.jpg",
                "width": 1200,
                "height": 675
              },
              {
                "src": "photography/variants/sunset-coda-6f51553249e9756f-1600.jpg",
                "width": 1600,
                "height": 900
              },
              {
                "src": "photography/variants/sunset-coda-6f51553249e9756f-2400.jpg",
                "width": 2400,
                "height": 1350
              }
            ],
            "webp": [
              {
                "src": "photography/variants/sunset-coda-6f51553249e9756f-600.webp",
                "width": 600,
                "height": 337
              },
              {
                "src": "photography/variants/sunset-coda-6f51553249e9756f-1200.webp",
                "width": 1200,
                "height": 675
              },
              {
                "src": "photography/variants/sunset-coda-6f51553249e9756f-1600.webp",
                "width": 1600,
                "height": 900
              },
              {
                "src": "photography/variants/sunset-coda-6f51553249e9756f-2400.webp",
                "width": 2400,
                "height": 1350
              }
            ]
          },
          "alt": "Orange sunset sky beside a glass facade with vertical mullions.",
          "theme": "Architecture",
          "place": "",
          "order": 6,
          "width": 5547,
          "height": 3120,
          "camera": "SONY ILCE-7M4",
          "lens": "SIGMA 60-600mm F4.5-6.3 DG DN OS Sports 023",
          "focalLength": "600mm",
          "shutterSpeed": "1/80s",
          "aperture": "f/6.3",
          "iso": "ISO 400",
          "date": "2025:09:28 19:19:30"
        },
        {
          "src": "photography/umeda-sky-circle.jpg",
          "thumb": "photography/thumbs/umeda-sky-circle.jpg",
          "preview": "photography/variants/umeda-sky-circle-700cd8d83e0bf84f-1600.jpg",
          "sources": {
            "jpeg": [
              {
                "src": "photography/variants/umeda-sky-circle-700cd8d83e0bf84f-600.jpg",
                "width": 600,
                "height": 600
              },
              {
                "src": "photography/variants/umeda-sky-circle-700cd8d83e0bf84f-1200.jpg",
                "width": 1200,
                "height": 1200
              },
              {
                "src": "photography/variants/umeda-sky-circle-700cd8d83e0bf84f-1600.jpg",
                "width": 1600,
                "height": 1600
              }
            ],
            "webp": [
              {
                "src": "photography/variants/umeda-sky-circle-700cd8d83e0bf84f-600.webp",
                "width": 600,
                "height": 600
              },
              {
                "src": "photography/variants/umeda-sky-circle-700cd8d83e0bf84f-1200.webp",
                "width": 1200,
                "height": 1200
              },
              {
                "src": "photography/variants/umeda-sky-circle-700cd8d83e0bf84f-1600.webp",
                "width": 1600,
                "height": 1600
              }
            ]
          },
          "alt": "Steel escalators cross a circular opening in the roof, with clouds beyond.",
          "theme": "Architecture",
          "place": "Osaka, Japan",
          "order": 7,
          "width": 1600,
          "height": 1600,
          "camera": "SONY ILCE-7M4",
          "lens": "SIGMA 24-70mm F2.8 DG DN Art 019",
          "focalLength": "70mm",
          "shutterSpeed": "1/800s",
          "aperture": "f/5.6",
          "iso": "ISO 100",
          "date": "2025:05:27 01:33:05"
        },
        {
          "src": "photography/tokyo-tower-framed.jpg",
          "thumb": "photography/thumbs/tokyo-tower-framed.jpg",
          "preview": "photography/variants/tokyo-tower-framed-ac4251d9ea4b77ab-1600.jpg",
          "sources": {
            "jpeg": [
              {
                "src": "photography/variants/tokyo-tower-framed-ac4251d9ea4b77ab-600.jpg",
                "width": 400,
                "height": 600
              },
              {
                "src": "photography/variants/tokyo-tower-framed-ac4251d9ea4b77ab-1200.jpg",
                "width": 800,
                "height": 1200
              },
              {
                "src": "photography/variants/tokyo-tower-framed-ac4251d9ea4b77ab-1600.jpg",
                "width": 1067,
                "height": 1600
              },
              {
                "src": "photography/variants/tokyo-tower-framed-ac4251d9ea4b77ab-2400.jpg",
                "width": 1600,
                "height": 2400
              }
            ],
            "webp": [
              {
                "src": "photography/variants/tokyo-tower-framed-ac4251d9ea4b77ab-600.webp",
                "width": 400,
                "height": 600
              },
              {
                "src": "photography/variants/tokyo-tower-framed-ac4251d9ea4b77ab-1200.webp",
                "width": 800,
                "height": 1200
              },
              {
                "src": "photography/variants/tokyo-tower-framed-ac4251d9ea4b77ab-1600.webp",
                "width": 1067,
                "height": 1600
              },
              {
                "src": "photography/variants/tokyo-tower-framed-ac4251d9ea4b77ab-2400.webp",
                "width": 1600,
                "height": 2400
              }
            ]
          },
          "alt": "Tokyo Tower viewed through the narrow frame of an urban staircase.",
          "theme": "Architecture",
          "place": "Tokyo, Japan",
          "order": 9,
          "width": 4519,
          "height": 6779,
          "camera": "SONY ILCE-7M4",
          "lens": "SIGMA 24-70mm F2.8 DG DN Art 019",
          "focalLength": "24mm",
          "shutterSpeed": "1/60s",
          "aperture": "f/20",
          "iso": "ISO 100",
          "date": "2025:06:07 00:50:55"
        },
        {
          "src": "photography/hong-kong-harbour-night.jpg",
          "thumb": "photography/thumbs/hong-kong-harbour-night.jpg",
          "preview": "photography/variants/hong-kong-harbour-night-3bf9af531fc32ae3-1600.jpg",
          "sources": {
            "jpeg": [
              {
                "src": "photography/variants/hong-kong-harbour-night-3bf9af531fc32ae3-600.jpg",
                "width": 600,
                "height": 400
              },
              {
                "src": "photography/variants/hong-kong-harbour-night-3bf9af531fc32ae3-1200.jpg",
                "width": 1200,
                "height": 800
              },
              {
                "src": "photography/variants/hong-kong-harbour-night-3bf9af531fc32ae3-1600.jpg",
                "width": 1600,
                "height": 1067
              },
              {
                "src": "photography/variants/hong-kong-harbour-night-3bf9af531fc32ae3-2400.jpg",
                "width": 2400,
                "height": 1600
              }
            ],
            "webp": [
              {
                "src": "photography/variants/hong-kong-harbour-night-3bf9af531fc32ae3-600.webp",
                "width": 600,
                "height": 400
              },
              {
                "src": "photography/variants/hong-kong-harbour-night-3bf9af531fc32ae3-1200.webp",
                "width": 1200,
                "height": 800
              },
              {
                "src": "photography/variants/hong-kong-harbour-night-3bf9af531fc32ae3-1600.webp",
                "width": 1600,
                "height": 1067
              },
              {
                "src": "photography/variants/hong-kong-harbour-night-3bf9af531fc32ae3-2400.webp",
                "width": 2400,
                "height": 1600
              }
            ]
          },
          "alt": "Hong Kong's illuminated skyline beside the harbour, with a tall tower, orange roads, and dark mountains behind.",
          "theme": "Architecture",
          "place": "Hong Kong",
          "order": 11,
          "width": 7008,
          "height": 4672,
          "camera": "SONY ILCE-7M4",
          "lens": "FE 70-200mm F2.8 GM OSS II",
          "focalLength": "89mm",
          "shutterSpeed": "1/60s",
          "aperture": "f/3.2",
          "iso": "ISO 6400",
          "date": "2026:09:03 11:00:35"
        }
      ]
    },
    {
      "title": "Landscape & Travel",
      "slug": "landscape-travel",
      "photos": [
        {
          "src": "photography/pine-branch-sunset.jpg",
          "thumb": "photography/thumbs/pine-branch-sunset.jpg",
          "preview": "photography/variants/pine-branch-sunset-de4f1599b750244f-1600.jpg",
          "sources": {
            "jpeg": [
              {
                "src": "photography/variants/pine-branch-sunset-de4f1599b750244f-600.jpg",
                "width": 600,
                "height": 449
              },
              {
                "src": "photography/variants/pine-branch-sunset-de4f1599b750244f-1200.jpg",
                "width": 1200,
                "height": 898
              },
              {
                "src": "photography/variants/pine-branch-sunset-de4f1599b750244f-1600.jpg",
                "width": 1600,
                "height": 1198
              },
              {
                "src": "photography/variants/pine-branch-sunset-de4f1599b750244f-2400.jpg",
                "width": 2400,
                "height": 1797
              }
            ],
            "webp": [
              {
                "src": "photography/variants/pine-branch-sunset-de4f1599b750244f-600.webp",
                "width": 600,
                "height": 449
              },
              {
                "src": "photography/variants/pine-branch-sunset-de4f1599b750244f-1200.webp",
                "width": 1200,
                "height": 898
              },
              {
                "src": "photography/variants/pine-branch-sunset-de4f1599b750244f-1600.webp",
                "width": 1600,
                "height": 1198
              },
              {
                "src": "photography/variants/pine-branch-sunset-de4f1599b750244f-2400.webp",
                "width": 2400,
                "height": 1797
              }
            ]
          },
          "alt": "A pine branch catches warm light against a softly blurred hillside and pale sky.",
          "theme": "Landscape & Travel",
          "place": "",
          "order": 5,
          "width": 3120,
          "height": 2336,
          "camera": "SONY ILCE-7M4",
          "lens": "SIGMA 60-600mm F4.5-6.3 DG DN OS Sports 023",
          "focalLength": "278.2mm",
          "shutterSpeed": "1/200s",
          "aperture": "f/5.6",
          "iso": "ISO 100",
          "date": "2025:04:12 19:35:20"
        },
        {
          "src": "photography/rider-by-sea.jpg",
          "thumb": "photography/thumbs/rider-by-sea.jpg",
          "preview": "photography/variants/rider-by-sea-a09e31c5cb2780cd-1600.jpg",
          "sources": {
            "jpeg": [
              {
                "src": "photography/variants/rider-by-sea-a09e31c5cb2780cd-600.jpg",
                "width": 600,
                "height": 251
              },
              {
                "src": "photography/variants/rider-by-sea-a09e31c5cb2780cd-1200.jpg",
                "width": 1200,
                "height": 502
              },
              {
                "src": "photography/variants/rider-by-sea-a09e31c5cb2780cd-1600.jpg",
                "width": 1600,
                "height": 670
              },
              {
                "src": "photography/variants/rider-by-sea-a09e31c5cb2780cd-2400.jpg",
                "width": 2400,
                "height": 1004
              }
            ],
            "webp": [
              {
                "src": "photography/variants/rider-by-sea-a09e31c5cb2780cd-600.webp",
                "width": 600,
                "height": 251
              },
              {
                "src": "photography/variants/rider-by-sea-a09e31c5cb2780cd-1200.webp",
                "width": 1200,
                "height": 502
              },
              {
                "src": "photography/variants/rider-by-sea-a09e31c5cb2780cd-1600.webp",
                "width": 1600,
                "height": 670
              },
              {
                "src": "photography/variants/rider-by-sea-a09e31c5cb2780cd-2400.webp",
                "width": 2400,
                "height": 1004
              }
            ]
          },
          "alt": "A rider sits on a seawall beside a red motorcycle, with ocean waves beyond and empty parking bays in the foreground.",
          "theme": "Landscape & Travel",
          "place": "",
          "order": 8,
          "width": 5943,
          "height": 2487,
          "camera": "SONY ILCE-7M4",
          "lens": "SIGMA 24-70mm F2.8 DG DN Art 019",
          "focalLength": "70mm",
          "shutterSpeed": "1/250s",
          "aperture": "f/10",
          "iso": "ISO 100",
          "date": "2025:06:05 02:25:28"
        }
      ]
    },
    {
      "title": "Street",
      "slug": "street",
      "photos": [
        {
          "src": "photography/japan-lantern-restaurant.jpg",
          "thumb": "photography/thumbs/japan-lantern-restaurant.jpg",
          "preview": "photography/variants/japan-lantern-restaurant-a97cce00073195ab-1600.jpg",
          "sources": {
            "jpeg": [
              {
                "src": "photography/variants/japan-lantern-restaurant-a97cce00073195ab-600.jpg",
                "width": 400,
                "height": 600
              },
              {
                "src": "photography/variants/japan-lantern-restaurant-a97cce00073195ab-1200.jpg",
                "width": 800,
                "height": 1200
              },
              {
                "src": "photography/variants/japan-lantern-restaurant-a97cce00073195ab-1600.jpg",
                "width": 1067,
                "height": 1600
              },
              {
                "src": "photography/variants/japan-lantern-restaurant-a97cce00073195ab-2400.jpg",
                "width": 1600,
                "height": 2400
              }
            ],
            "webp": [
              {
                "src": "photography/variants/japan-lantern-restaurant-a97cce00073195ab-600.webp",
                "width": 400,
                "height": 600
              },
              {
                "src": "photography/variants/japan-lantern-restaurant-a97cce00073195ab-1200.webp",
                "width": 800,
                "height": 1200
              },
              {
                "src": "photography/variants/japan-lantern-restaurant-a97cce00073195ab-1600.webp",
                "width": 1067,
                "height": 1600
              },
              {
                "src": "photography/variants/japan-lantern-restaurant-a97cce00073195ab-2400.webp",
                "width": 1600,
                "height": 2400
              }
            ]
          },
          "alt": "Red and cream lanterns frame an open restaurant doorway and diners.",
          "theme": "Street",
          "place": "Japan",
          "order": 10,
          "width": 1872,
          "height": 2808,
          "camera": "SONY ILCE-7M4",
          "lens": "SIGMA 24-70mm F2.8 DG DN Art 019",
          "focalLength": "35.7mm",
          "shutterSpeed": "1/80s",
          "aperture": "f/3.2",
          "iso": "ISO 400",
          "date": "2025:05:29 08:16:11"
        }
      ]
    }
  ]
};
